### ISSUE TITLE
Add logging for BagDiscover routine

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/zorya#10]
Figure out what is logged--and how error handling happens--when bags fail validation.

**Comment by helrond** [comment]
I think basically what needs to happen here is returning exceptions (rather than printing them) out of the `run` methods of classes.

**Comment by bonniegee** [comment]
When a bag fails validation, a user needs to know why it failed validation, and the original name of the bag. This logging should happen in Zodiac.
