### ISSUE TITLE
Services are timing out and restarting with large (>5GB) packages

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/zorya#108]
## Is your feature request related to a problem? Please describe.
Services, particularly related to creating TAR files, are timing out on production with >5GB packages and restarting while already in process. This is causing the same processes to run simultaneously, which can tie up resources and cause failures elsewhere.

## Describe the solution you'd like
We could implement an approach like  RockefellerArchiveCenter/pictor#98 . Do you think this is a reasonable approach, @helrond ?

## Describe alternatives you've considered
We may want to make bigger changes to this application to handle large packages, but we need a short-term fix.

**Comment by helrond** [comment]
@bonniegee I think so - let's try it first with Pictor and see if it works there first?
