### ISSUE TITLE
Discover Bags service cannot handle TAR archives from certain sources

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/zorya#164]
## Is your feature request related to a problem? Please describe.
TAR archives from DART Runner behave differently when extracted than the previous TAR archives that Zorya has handled. This has caused weird behavior in the Discover Bags service that causes the service to fail.

Currently, it is expected that the first value of TarFile.getnames() is the bag directory name. However, for TAR archives from DART Runner, TarFile.getnames() only produced the files within the directory (and not the directory itself).

```
>>> bag_path
'/Users/bonniegordon/Downloads/23ab79f9c9514b52b619dfa319816488.tar'
>>> tf.getnames()[0]
'23ab79f9c9514b52b619dfa319816488/data/01.tif'
>>> bag_path = "/Users/bonniegordon/.dart/bags/37bd98bbafe54b77aff5850b80e7299f.tar"
>>> tf = tarfile.open(bag_path, 'r')
>>> tf.getnames()[0]
'37bd98bbafe54b77aff5850b80e7299f'
```

## Describe the solution you'd like
Check that `tf.getnames()[0]` does not end in a file extension, and if it does, parse it for the bag name.

**Comment by helrond** [comment]
I think that we can probably just do `tf.getnames()[0].split('/')[0]` since that will (I think) result in the desired output in either case.
