### ISSUE TITLE
Change port

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/zorya#57]
## Is your feature request related to a problem? Please describe.
The port is currently 8000, which may cause clashes when this is deployed.

## Describe the solution you'd like
Change the port this application is running on to ~~8007~~ 8011.

## Additional context
Are there any other considerations in changing the port, @helrond ?

**Comment by helrond** [comment]
@bonniegee Looks like port 8007 is already taken on prod and dev by Pisces. 

You can see which ports are already taken by running `netstat -tulpn` or by checking the Apache config file `/etc/httpd/conf/httpd.conf`

You don't necessarily need to use the same port on prod and dev but it does make things a little easier. I'd consider going to 8011.
