### ISSUE TITLE
Use the BasePackage from Asterism instead of a custom model

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/zorya#70]
## Is your feature request related to a problem? Please describe.
The Bag model serializer is causing invalid JSON to be created because of incorrect names in the Bag model. This would likely be mitigated if the BasePackage from Asterism was used instead of a custom model.

## Describe the solution you'd like
Use the BasePackage from Asterism as the basis of the Bag model.

**Comment by bonniegee** [comment]
@helrond One minor issue I'm running into with this is that we're not currently using the "Process Status" field in Zorya; should I create some and update this field in each service, or try another approach?

**Comment by helrond** [comment]
@bonniegee If you're getting an error, you could try setting PROCESS_STATUS_CHOICES to an empty tuple and see if that works?

**Comment by bonniegee** [comment]
Noting here that we should be updating the services to update the process status field.
