### ISSUE TITLE
Save the refid to the bag-info.txt file

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/zorya#71]
## Is your feature request related to a problem? Please describe.
The ArchivesSpace refid associated with a bag needs to be accessed by other microservices.

## Describe the solution you'd like
Save the directory name (presumed to be a refid) as `ArchivesSpace-RefID` in the bag-info file.

## Describe alternatives you've considered
The refid could be provided in the serialized bag data file sent to Zorya.

**Comment by helrond** [comment]
Bags are expected to have a `ArchivesSpace-URI` value in bag-info.txt, which will solve this problem.
