### ISSUE TITLE
Add static BagIt profile

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/zorya#76]
## Is your feature request related to a problem? Please describe.
The BagIt profile for digitized and legacy digital bags is currently being stored in a Gist. Storing a BagIt profile within this application would improve maintainability and ease of finding the profile.

## Describe the solution you'd like
Add BagIt profile for digitized and legacy digital bags.

**Comment by HaSistrunk** [comment]
When this is done, we should review the [Project Electron website](https://projectelectron.rockarch.org/scripts/) to decide if we want to adjust how we link to the profile ([currently on Github here](https://github.com/RockefellerArchiveCenter/project_electron/blob/gh-pages/content/scripts.md)).

**Comment by helrond** [comment]
@HaSistrunk that's a different use case - this is a BagIt Profile specifically for validating bags of digitized content.
