### ISSUE TITLE
Download bags from S3 in BagDiscoverer routine

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/zorya#83]
## Is your feature request related to a problem? Please describe.
The current BagDiscoverer routine expects to find bags by checking for a directory. As part of implementing the DART digitization pipeline, we will want to use the S3 API to download bags from a bucket.

## Describe the solution you'd like
Instead of looking at the contents of a directory, the BagDiscoverer routine should look to see what is in an S3 bucket and download those items. We will also want to delete the bags from S3 after successfully downloading and saving.

Is there any reason why we would continue to want to also check a directory @helrond ? The legacy born digital workflow will also use DART.

**Comment by helrond** [comment]
I think the way to have our cake and eat it too would be to have the download be a separate service (rather than lumping it in with the DiscoverBags service). That way, there could be multiple ways of getting files into that discovery directory.
